growing_commander_server/views/app.py
from flask import render_template, request, url_for, flash, redirect, Blueprint
from flask_login import login_user, logout_user, login_required

from growing_commander_server.forms import LoginForm
from growing_commander_server.models import User, Measurement
from growing_commander_server.tables import UserTable, MeasurementsTable

app_blueprint = Blueprint('app_blueprint', __name__)


@app_blueprint.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        form = LoginForm(request.form)
        if form.validate():
            login_user(form.user)
            flash("Successfully logged in as %s." % form.user.name, "success")
            return redirect(url_for("app_blueprint.overview"))
    else:
        form = LoginForm()
    return render_template("login_page.html", form=form)


@login_required
@app_blueprint.route("/logout/")
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('app_blueprint.login'))


@app_blueprint.route('/overview')
@login_required
def overview():
    return render_template('homepage.html')


@app_blueprint.route('/users')
@login_required
def users():
    all_users = User.query.order_by(User.registered_on.desc()).all()
    table = UserTable(all_users, border=True)
    return render_template('users.html', table=table)


@app_blueprint.route('/measures')
@login_required
def measures():
    tables = []
    measurements = Measurement.query.all()
    tables.append(MeasurementsTable(measurements, border=True))
    return render_template('measures.html', tables=tables)


@app_blueprint.route('/commands')
@login_required
def commands():
    return render_template('api_overview.html')

growing_commander_server/templates/api_overview.html
{% extends "base.html" %}
{% block content_title %}API overview{% endblock %}
{% block content %}
    <div>
    <h1>Auth API</h1>
        <div>
            '/auth/login' </br>
            POST: 'name', 'password'
        </div>
    </div>
    <div>
    <h1>Measurement API</h1>
        <div>
            /measurement/ </br>
            POST: 'auth_token', 'data'
        </div>
        <div>
            /measurement/&lt;measurement_id&gt; </br>
            GET: 'auth_token',
        </div>
    </div>
{% endblock %}

growing_commander_server/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %} | My Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <style type="text/css"> body { padding-top: 60px; } </style>
        {% block extra_styles %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
			  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
			  crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% block extra_scripts %}{% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('app_blueprint.overview') }}">Overview</a></li>
                        <li><a href="{{ url_for('app_blueprint.commands') }}">Commands</a></li>
                        <li><a href="{{ url_for('app_blueprint.measures') }}">Measures</a></li>
                        <li><a href="{{ url_for('app_blueprint.users') }}">Users</a></li>
                        <li><a href="{{ url_for('app_blueprint.logout') }}">Log out</a></li>
                        {% block extra_nav %}{% endblock %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <h1>
                        {% block content_title %}{% endblock %}
                    </h1>
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-3">
                    {% block sidebar %}
                    <ul class="well nav nav-stacked">
                        <li>
                            <a href="#">Sidebar item</a>
                        </li>
                    </ul>
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

growing_commander_server/templates/homepage.html
{% extends "base.html" %}
{% block content_title %}Welcome to my blog{% endblock %}
{% block content %}
    {% if number %}
        <p>Your number is {{ number|int }}</p>
        <ul>
            {% for i in range(number|int) %}
                {% if i is divisibleby 2 %}
                    <li>{{ i }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>No number specified.</p>
    {% endif %}
    <p>Your name is {{ name|default('<unknown>', True) }}.</p>
{% endblock %}

growing_commander_server/templates/login_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <style type="text/css"> body { padding-top: 60px; } </style>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <h1>
                        Log in
                    </h1>
                    <form action="{{ url_for('app_blueprint.login')}}" class="form form-horizontal" method="post">
                        {% from "macros/form_field.html" import form_field %}
                        {{ form_field(form.name) }}
                        {{ form_field(form.password) }}
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="submit" class="btn btn-default">Log in</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

growing_commander_server/templates/measures.html
{% extends "base.html" %}
{% block content_title %}List of measurements{% endblock %}
{% block content %}
    {% for measurements in tables %}
        <div>
        {{ measurements }}
        </div>
    {% endfor %}
{% endblock %}

growing_commander_server/templates/users.html
{% extends "base.html" %}
{% block content_title %}List of users{% endblock %}
{% block content %}
    {{ table }}
{% endblock %}